services:
  - type: web
    name: operator-management-system
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/OperatorManagementSystem-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
    plan: free
