services:
  - type: web
    name: operator-management-system
    env: docker
    plan: free
    branch: deploytest
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - target/OperatorManagementSystem-0.0.1-SNAPSHOT.jar
